### PR TITLE
Add support for .NET 4.6 by creating a multi-target project

### PR DESCRIPTION
**Pull request by kind-serge**
@psibernetic, I deleted the .NET 4.5 project and created a single multi-target one. Explicitly listed .NET 4.6. Did not bump the version.

### CODE REVIEW

**Comment by aidapsibr** [comment]
Nice, I was actually going to do this today! The only thing that needs changed is I learned last night net45 can not be targeted by any code environment other than where a machine has Visual Studio. As such, I consider 4.5 beyond supportable, so will bump to 4.5.2

**Comment by kind-serge** [comment]
Oh, good to know, and honestly, f*** anything that targets .NET 4.5 and lower :)

**Comment by aidapsibr** [comment]
@abalfour will push the net452 in a new pr, so this is good.

**Comment by aidapsibr** [comment]
Got to take a look at CI though, don't think it was setup.

**Comment by kind-serge** [comment]
I complied and ran tests - all looks good. The generated NuGet package also looks good.

**Comment by kind-serge** [comment]
btw @psibernetic did you see the XML doc file path change? Just a tip how to unify regardless build configuration: `<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>`

**Comment by aidapsibr** [comment]
I did not, that's nice.

**Pull request merged**
